Fix for `alluxio.wire` enum instances
Reason: current implementation is not aligned with the REST API spec. Example:

```
from alluxio import Client
from alluxio.option import ListStatus
from alluxio.wire import LOAD_METADATA_TYPE_ALWAYS

client = Client(host=<some-host>, port=39999)
opt = ListStatus(load_metadata_type=LOAD_METADATA_TYPE_ALWAYS, recursive=True)
client.list_status("/", opt)
```

Result:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../alluxio-py/alluxio/client.py", line 280, in list_status
    result = self._post(url, opt).json()
  File ".../alluxio-py/alluxio/client.py", line 137, in _post
    _check_response(response)
  File ".../alluxio-py/alluxio/client.py", line 51, in _check_response
    error = response.json()
  File ".../.pyenv/versions/3.9.7/envs/alluxio-py/lib/python3.9/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File ".../.pyenv/versions/3.9.7/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File ".../.pyenv/versions/3.9.7/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File ".../.pyenv/versions/3.9.7/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Underlying cause:

```
# fails:
$ curl -X POST http://<host>:<port>/api/v1/paths///list-status -d '{"loadMetadataType": "Always"}' -H 'Content-Type: application/json'
Cannot deserialize value of type `com.google.protobuf.Descriptors$EnumDescriptor` from String "Always": value not one of declared Enum instance names
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 22]

# succeeds:
$ curl -X POST http://<host>:<port>/api/v1/paths///list-status -d '{"loadMetadataType": "ALWAYS"}' -H 'Content-Type: application/json'
```

## Auxiliary additions

- Toy Alluxio cluster for playground purposes
- Integration test suite (for `list_status()` and `get_status()` methods only)
- `GetStatus` opt got a parameter `load_metadata_type`