Fix doc issues
- WARNING: html_static_path entry '_static' does not exist
- Failure of doc generation:

```
$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.3.6
loading translations [en]... done
loading pickled environment... failed: Can't get attribute '_stable_repr_object' on <module 'sphinx.builders.html' from '.../.pyenv/versions/3.9.7/envs/alluxio-py/lib/python3.9/site-packages/sphinx/builders/html.py'>

Exception occurred:
  File ".../.pyenv/versions/3.9.7/envs/alluxio-py/lib/python3.9/site-packages/sphinx/jinja2glue.py", line 16, in <module>
    from jinja2 import FileSystemLoader, BaseLoader, TemplateNotFound, \
ImportError: cannot import name 'contextfunction' from 'jinja2' (.../.pyenv/versions/3.9.7/envs/alluxio-py/lib/python3.9/site-packages/jinja2/__init__.py)
The full traceback has been saved in /var/folders/jh/8yfsyb6j3pz432fj878403cc0000gn/T/sphinx-err-2ixttfbz.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 1
```

- .../alluxio-py/alluxio/exceptions.py:docstring of alluxio.exceptions.FailedPreconditionError:8: ERROR: Unexpected indentation.